/**
 * vite-plugin-content-keys  (plain JS — works in all environments)
 *
 * Build-time Vite plugin that scans every src/**\/*.tsx file for:
 *   1. <EditableContent contentKey="key" fallback="val" />
 *   2. getContent('key', 'fallback')
 *
 * Exposes the result as a virtual module `virtual:content-keys`.
 */

import { readFileSync, readdirSync, statSync } from 'fs';
import { join, relative } from 'path';

const VIRTUAL_ID = 'virtual:content-keys';
const RESOLVED_ID = '\0virtual:content-keys';

// ─── File walker ──────────────────────────────────────────────────────────────
function walkSrc(dir, files = []) {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const stat = statSync(full);
    if (stat.isDirectory()) {
      if (!['node_modules', 'dist', 'supabase', '.git', 'public'].includes(entry)) {
        walkSrc(full, files);
      }
    } else if (/\.(tsx?|jsx?)$/.test(entry)) {
      files.push(full);
    }
  }
  return files;
}

// ─── Scanner ──────────────────────────────────────────────────────────────────
function scanFiles(root) {
  const entries = [];
  const seen = new Set();

  let srcDir;
  try {
    srcDir = join(root, 'src');
    statSync(srcDir);
  } catch {
    return entries;
  }

  const files = walkSrc(srcDir);

  for (const absPath of files) {
    const relPath = relative(root, absPath).replace(/\\/g, '/');
    let source;
    try {
      source = readFileSync(absPath, 'utf-8');
    } catch {
      continue;
    }

    // Pattern 1: contentKey="key" ... fallback="val"
    for (const m of source.matchAll(
      /contentKey=["'`]([^"'`]+)["'`][^>]*?fallback=["'`]([^"'`]*)["'`]/gs,
    )) {
      const key = m[1];
      if (!seen.has(key)) {
        seen.add(key);
        entries.push({ key, fallback: m[2], type: 'editableContent', file: relPath });
      }
    }

    // Pattern 2: fallback="val" ... contentKey="key" (reversed)
    for (const m of source.matchAll(
      /fallback=["'`]([^"'`]*)["'`][^>]*?contentKey=["'`]([^"'`]+)["'`]/gs,
    )) {
      const key = m[2];
      if (!seen.has(key)) {
        seen.add(key);
        entries.push({ key, fallback: m[1], type: 'editableContent', file: relPath });
      }
    }

    // Pattern 3: contentKey="key" with no fallback
    for (const m of source.matchAll(/contentKey=["'`]([^"'`]+)["'`]/g)) {
      const key = m[1];
      if (!seen.has(key)) {
        seen.add(key);
        entries.push({ key, fallback: '', type: 'editableContent', file: relPath });
      }
    }

    // Pattern 4: getContent('key', 'fallback')
    for (const m of source.matchAll(/getContent\(["'`]([^"'`]+)["'`]\s*,\s*["'`]([^"'`]*)["'`]/g)) {
      const key = m[1];
      if (!seen.has(key)) {
        seen.add(key);
        entries.push({ key, fallback: m[2], type: 'getContent', file: relPath });
      }
    }

    // Pattern 5: getContent('key') with no fallback
    for (const m of source.matchAll(/getContent\(["'`]([^"'`]+)["'`]\s*[),]/g)) {
      const key = m[1];
      if (!seen.has(key)) {
        seen.add(key);
        entries.push({ key, fallback: '', type: 'getContent', file: relPath });
      }
    }
  }

  return entries;
}

// ─── Virtual module code generator ───────────────────────────────────────────
function generateModule(entries) {
  const json = JSON.stringify(entries, null, 0);
  return `// AUTO-GENERATED by vite-plugin-content-keys — do not edit\nexport const CONTENT_KEYS = ${json};\n`;
}

// ─── Plugin ───────────────────────────────────────────────────────────────────
export default function contentKeysPlugin() {
  let root = process.cwd();

  return {
    name: 'vite-plugin-content-keys',

    configResolved(config) {
      root = config.root;
    },

    resolveId(id) {
      if (id === VIRTUAL_ID) return RESOLVED_ID;
    },

    load(id) {
      if (id === RESOLVED_ID) {
        const entries = scanFiles(root);
        return generateModule(entries);
      }
    },

    handleHotUpdate({ file, server }) {
      if (file.includes('/src/') && /\.(tsx?|jsx?)$/.test(file)) {
        const mod = server.moduleGraph.getModuleById(RESOLVED_ID);
        if (mod) server.moduleGraph.invalidateModule(mod);
        server.hot.send({ type: 'full-reload' });
      }
    },
  };
}